[profile.default]
src = 'src'
out = 'out'
test = 'test'
libs = ['lib']
solc_version = '0.8.24'
optimizer = true
optimizer_runs = 200
bytecode_hash = 'ipfs'
via_ir = true
fs_permissions = [
  { access = 'read', path = './' }
]


